security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$pUaaC6cwub1NkwNvSm/FnuR3rli8YgjIg1Di68hqX4J1TnGpLc2AC
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$ROCN/MhD6U0Rsr0xsrHT/.RETqtgm8nQmdbOsC2o4w4RyHrUhXcvS
                        roles: 'ROLE_ADMIN'
                    matt:
                        password: $2y$12$4UWrrc1pkskcCMDpcj4XzeLVsn5Tlk4zkQJAyrSaoDnOnY1wgHUH2
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /
