security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$kZ5yb4NmAa.NdNVxMT0qq.obGDSfvUq7BqAh2CqhhlkIX5ZAihkba
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$MfM37glOI6ERb6tzGYD.LO87YvrGzu5wm46M3L8D3pfwXcrxKS5qW
                        roles: 'ROLE_ADMIN'
                    matt:
                        password: $2y$12$X.ZCax2stsn0dLL7hqA/OO6xt/qem816T7GaZ/VrLuR9lp6ilH0YK
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

            logout:
              path: /logout
              target: /