<?php

namespace AppBundle\Repository;

/**
 * ElectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
