<?php

namespace AppBundle\Repository;

/**
 * CountyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountyRepository extends \Doctrine\ORM\EntityRepository
{
}
