<?php

namespace AppBundle\Repository;

/**
 * BllogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BllogRepository extends \Doctrine\ORM\EntityRepository
{
}
